# Generated by Django 3.0.2 on 2020-01-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detail', models.TextField(max_length=5000)),
                ('addition', models.CharField(default=False, max_length=5000)),
                ('background', models.CharField(default=False, max_length=5000)),
                ('problem', models.CharField(default=False, max_length=5000)),
                ('link', models.CharField(default=False, max_length=100)),
                ('language', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_project', to='project.School')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_project', to='account.Supervisor')),
            ],
        ),
    ]
