# Generated by Django 3.0.2 on 2020-01-31 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200128_1525'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_finishedproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to='account.Hod')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to='project.Department')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to='project.Groups')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
