# Generated by Django 3.0.2 on 2020-01-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200131_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
