# Generated by Django 3.0.2 on 2020-01-31 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinishedProject',
        ),
    ]
