# Generated by Django 3.0.2 on 2020-01-24 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('group_email', models.CharField(max_length=250)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='project.Department')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=2500)),
                ('school_location', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=500)),
                ('project_description', models.TextField(max_length=10000)),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='GroupProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_type', models.CharField(choices=[('project_title', 'Project Title'), ('project_proposal', 'Project Proposal'), ('project_erd', 'Project (ERD)'), ('time_management', 'Time Management'), ('project_scope', 'Project scope'), ('project_cost', 'Project Cost'), ('project_backend', 'Project Backend'), ('project_frontend', 'Project Frontend'), ('project_test', 'Project Test'), ('deployment', 'Deployment'), ('project_book', 'Project Book')], default='project_title', max_length=100)),
                ('file_title', models.CharField(max_length=200)),
                ('file_description', models.FileField(max_length=2500, upload_to='')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_progress', to='project.Groups')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='school_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='project.School'),
        ),
    ]
