# Generated by Django 3.0.2 on 2020-01-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200131_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproject',
            name='introduction',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='finalproject',
            name='problem_statement',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='finalproject',
            name='scope',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='finalproject',
            name='source_code',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
